export const contextFields = {
  name: "Employee Name",
  department: "Department of the Employee",
  role: "Role of the Employee",
  email: "Email of the Employee",
  phone: "Employee Mobile Number",
  location: "Work Location of the Employee",
  dateOfJoining: "Employee Date of Joining",
};

export const data = [
  {
    name: "Alice Verma",
    department: "Engineering",
    role: "Frontend Developer",
    email: "alice.verma@company.com",
    phone: "9123456789",
    location: "Bangalore",
    dateOfJoining: "2022-03-14",
  },
  {
    name: "Rohan Mehta",
    department: "Marketing",
    role: "Content Strategist",
    email: "rohan.mehta@company.com",
    phone: "9876543210",
    location: "Mumbai",
    dateOfJoining: "2023-06-10",
  },
  {
    name: "Priya Sharma",
    department: "HR",
    role: "Talent Acquisition Lead",
    email: "priya.sharma@company.com",
    phone: "9012345678",
    location: "Delhi",
    dateOfJoining: "2021-11-01",
  },
  {
    name: "Siddharth Iyer",
    department: "Engineering",
    role: "Backend Developer",
    email: "siddharth.iyer@company.com",
    phone: "8899776655",
    location: "Bangalore",
    dateOfJoining: "2024-01-23",
  },
  {
    name: "Tanya D'Souza",
    department: "Design",
    role: "UI/UX Designer",
    email: "tanya.dsouza@company.com",
    phone: "9988776655",
    location: "Remote",
    dateOfJoining: "2023-09-18",
  },
  {
    name: "Aakash Singh",
    department: "Engineering",
    role: "DevOps Engineer",
    email: "aakash.singh@company.com",
    phone: "9112233445",
    location: "Hyderabad",
    dateOfJoining: "2022-07-11",
  },
  {
    name: "Meera Nair",
    department: "Finance",
    role: "Financial Analyst",
    email: "meera.nair@company.com",
    phone: "9001122334",
    location: "Chennai",
    dateOfJoining: "2020-05-03",
  },
  {
    name: "Rajiv Menon",
    department: "Sales",
    role: "Regional Sales Manager",
    email: "rajiv.menon@company.com",
    phone: "9811223344",
    location: "Kolkata",
    dateOfJoining: "2019-12-15",
  },
  {
    name: "Neha Kapoor",
    department: "Product",
    role: "Product Manager",
    email: "neha.kapoor@company.com",
    phone: "8776655443",
    location: "Remote",
    dateOfJoining: "2023-02-08",
  },
  {
    name: "Karan Bhatt",
    department: "Engineering",
    role: "QA Engineer",
    email: "karan.bhatt@company.com",
    phone: "9887766554",
    location: "Pune",
    dateOfJoining: "2022-11-27",
  },
  {
    name: "Simran Gill",
    department: "Customer Support",
    role: "Support Executive",
    email: "simran.gill@company.com",
    phone: "9123445566",
    location: "Delhi",
    dateOfJoining: "2021-06-19",
  },
  {
    name: "Abhay Deshmukh",
    department: "Legal",
    role: "Legal Advisor",
    email: "abhay.deshmukh@company.com",
    phone: "9334455667",
    location: "Mumbai",
    dateOfJoining: "2018-10-30",
  },
  {
    name: "Divya Rathi",
    department: "Engineering",
    role: "Machine Learning Engineer",
    email: "divya.rathi@company.com",
    phone: "9090901122",
    location: "Bangalore",
    dateOfJoining: "2023-04-12",
  },
  {
    name: "Zaid Qureshi",
    department: "Marketing",
    role: "SEO Specialist",
    email: "zaid.qureshi@company.com",
    phone: "8888777766",
    location: "Hyderabad",
    dateOfJoining: "2022-12-01",
  },
  {
    name: "Sneha Patel",
    department: "Product",
    role: "Associate Product Manager",
    email: "sneha.patel@company.com",
    phone: "8899001122",
    location: "Mumbai",
    dateOfJoining: "2024-03-21",
  },
  {
    name: "Anil Jadhav",
    department: "IT",
    role: "System Administrator",
    email: "anil.jadhav@company.com",
    phone: "9988774455",
    location: "Pune",
    dateOfJoining: "2020-08-14",
  },
  {
    name: "Nikita Shetty",
    department: "Design",
    role: "Visual Designer",
    email: "nikita.shetty@company.com",
    phone: "9080706050",
    location: "Bangalore",
    dateOfJoining: "2023-10-01",
  },
  {
    name: "Vikram Chauhan",
    department: "Sales",
    role: "Inside Sales Executive",
    email: "vikram.chauhan@company.com",
    phone: "8877665544",
    location: "Gurgaon",
    dateOfJoining: "2021-01-10",
  },
  {
    name: "Fatima Khan",
    department: "HR",
    role: "HR Operations Specialist",
    email: "fatima.khan@company.com",
    phone: "9765432109",
    location: "Delhi",
    dateOfJoining: "2019-04-05",
  },
  {
    name: "Arjun Rao",
    department: "Engineering",
    role: "Tech Lead",
    email: "arjun.rao@company.com",
    phone: "9666443322",
    location: "Hyderabad",
    dateOfJoining: "2018-07-17",
  },
  {
    name: "Pooja Desai",
    department: "Customer Support",
    role: "Customer Success Manager",
    email: "pooja.desai@company.com",
    phone: "9345678800",
    location: "Ahmedabad",
    dateOfJoining: "2022-09-30",
  },
  {
    name: "Ritik Agarwal",
    department: "Finance",
    role: "Accounts Manager",
    email: "ritik.agarwal@company.com",
    phone: "9654321008",
    location: "Kolkata",
    dateOfJoining: "2021-05-28",
  },
].map((d) => {
  const obj = {};

  Object.entries(d).forEach(([key, value]) => {
    // @ts-ignore
    obj[contextFields[key]] = value;
  });

  return obj;
});
